name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
            binary_suffix: ".exe"
          - goos: windows
            goarch: arm64
            binary_suffix: ".exe"
          - goos: linux
            goarch: amd64
            binary_suffix: ""
          - goos: linux
            goarch: arm64
            binary_suffix: ""
          - goos: darwin
            goarch: amd64
            binary_suffix: ""
          - goos: darwin
            goarch: arm64
            binary_suffix: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w" -o goredis-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.binary_suffix }} ./app

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: goredis-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.binary_suffix }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
